### ISSUE TITLE
Arroseur (redpitaya on the web) is down

### ISSUE THREAD

**Issue by lneuhaus** [pyrpl-fpga/pyrpl#296]

**Comment by lneuhaus** [comment]
I still cannot connect to arroseur. Are we sure that ddns is still working?

**Comment by lneuhaus** [comment]
i simply tried `ssh arroseur.ddns.net`

**Comment by SamuelDeleglise** [comment]
I believe the update of the dns that should run on my raspberry pi is down. I am working on it right now...

**Comment by SamuelDeleglise** [comment]
I think it should work now ?

**Comment by lneuhaus** [comment]
Can you commit some whitespace to master to check it? Im getting off thr
train now..

**Comment by lneuhaus** [comment]
Or just go on travis-ci.org and relaunch the last build

On Jul 1, 2017 5:56 PM, wrote:
>
> Can you commit some whitespace to master to check it? Im getting off thr
train now..
>
> On Jul 1, 2017 5:53 PM, "SamuelDeleglise" <notifications@github.com>
wrote:

**Comment by SamuelDeleglise** [comment]
It seems to work now

**Comment by lneuhaus** [comment]
arroseur is still down, so repo master branch still indicates "build failing" while the code is provably okay...
