### ISSUE TITLE
How to lock cavity with Q factor 100 to lock to stabilised He-Ne laser using pyrpl GUI

### ISSUE THREAD

**Issue by Sridhargovindan** [pyrpl-fpga/pyrpl#539]
I am new to using PYRPL program. I could get GUI using standalone binary exe file in windows and i could connect to red pitaya.
I am able to drive scanning confocal FP interferometer. Now i want to lock at the side of the fringe using lock box or PID. 
Please suggest.

**Comment by michaelcroquette** [comment]
I think you can find the answer to your question in the docs and in this video:
https://youtu.be/WnFkz1adhgs?si=CMAXr8JlIVD_mkh4
